require([
    "/js/lib/bootstrap-transition.js",
    "/js/lib/bootstrap-modal.js",
    "/js/lib/bootstrap-dropdown.js",
    "/js/lib/bootstrap-alert.js",
    "order!/js/lib/modestmaps.js",
    "order!/js/confighelpers.js",
    "order!/js/nodes.js",
    "order!/js/spotlight.js",
    "order!/js/modestmaps.markers.js",
    "order!/js/complexcity.js",
    "order!/js/worker.js"
]);